### ISSUE TITLE
Style 클론 적용

### ISSUE THREAD

**Issue by anyl92** [wanted-pre-onboarding-team-12th-7/pre-onboarding-12th-3-7#17]
## Todo
- [x] 기본 레이아웃 적용
- [x] 검색 바 스타일 적용
- [x] X 버튼 클릭 시 키워드 삭제
- [x] 검색내역 및 최근 검색어 스타일 적용
- [x] 추천 검색어 스타일 적용
